- name: Python3.x virtualenv setup
  become: yes
  pip: virtualenv={{ virtualenv_path_3 }} requirements={{ requirements_path }}/requirements.txt virtualenv_python=python3.4 virtualenv_site_packages=yes

