- name: Install packages
  become: true
  #become_user: sudo
  apt: pkg={{ item }} state=installed  update_cache=yes
  with_items:
    
    #PREREQ
    - build-essential
    #DATABASE
    - postgresql
    - libpq-dev
    - python-psycopg2

    #PYTHON COMMON 
    - python-setuptools
  
    #PYTHON 3.x
    - python3-dev
    - python3-setuptools
    - python3-pip 
    - python-virtualenv
    #SCIPY STACK
    - python3-numpy
    - python3-scipy
    - python3-matplotlib
    - python3-pandas
 
    #MISC
    - tree
#DATABASE CONFIG
- name: Add django user
  become: true
  user: name=django password=django

- name: Create Database
  become: yes
  become_user: postgres
  postgresql_db: name={{ db_name }}

- name: Create User
  become: yes
  become_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_password }} state=present role_attr_flags=CREATEDB,NOSUPERUSER

- name: Provide user with DB permissions
  become: yes
  become_user: postgres
  postgresql_user: user={{ db_user }} db={{ db_name }} priv=ALL






